# interactive pyton notebooks ipynbs

version: "2.3"

services:
  pytorch-script:
    runtime: nvidia
    image: pytorch-script
    build: .
    ipc: host
    ports:
      - 8888:8888
    volumes:
      - ./ipynbs:/workspace/ipynbs
      - ./data:/workspace/data
      - ./outputs:/workspace/outputs
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
  #  command: python main.py
    command: jupyter notebook --allow-root --ip=0.0.0.0 --no-browser --NotebookApp.token=abc123